/// Code generation module
/// 
/// Currently generates C code as an intermediate step.
/// Future: LLVM backend for native code generation.
/// 
/// Phase 2: Fixed variable declarations and type tracking

use crate::ir::{IrModule, IrFunction, IrInstruction, IrValue, IrType, IrLiteral, IrParameter, IntType, FloatType};
use std::collections::{HashMap, HashSet};

/// Context for tracking variables and their types during code generation
struct CodegenContext {
    /// Maps variable/temporary names to their C types
    var_types: HashMap<String, String>,
    /// Tracks which variables have been declared
    declared: HashSet<String>,
    /// Current indentation level
    indent: usize,
    /// Closure tracking: variable/temp name -> generated closure function name
    closure_functions: HashMap<String, String>,
    /// Temporary tracking for closure values
    temp_to_closure: HashMap<String, String>,
}

impl CodegenContext {
    fn new() -> Self {
        Self {
            var_types: HashMap::new(),
            declared: HashSet::new(),
            indent: 1,
            closure_functions: HashMap::new(),
            temp_to_closure: HashMap::new(),
        }
    }

    fn register_var(&mut self, name: String, c_type: String) {
        self.var_types.insert(name, c_type);
    }

    fn get_type(&self, name: &str) -> Option<&String> {
        self.var_types.get(name)
    }

    fn indent_str(&self) -> String {
        "    ".repeat(self.indent)
    }
}

#[derive(Clone)]
struct ClosureDef {
    closure_id: usize,
    params: Vec<IrParameter>,
    body: Vec<IrInstruction>,
}

/// Generate C code from IR
pub fn ir_to_c(module: &IrModule) -> Result<String, String> {
    let mut output = String::new();
    let closure_defs = collect_closure_defs(module);
    
    // C header with runtime include
    output.push_str("/* Generated by Falcon Compiler */\n");
    output.push_str("#include <stdio.h>\n");
    output.push_str("#include <stdlib.h>\n");
    output.push_str("#include <stdint.h>\n");
    output.push_str("#include <stdbool.h>\n");
    output.push_str("#include <string.h>\n\n");
    
    // Forward declarations for Falcon runtime
    output.push_str("/* Falcon Runtime Declarations */\n");
    output.push_str("void falcon_panic(const char* msg);\n");
    output.push_str("void falcon_println(const char* s);\n");
    output.push_str("void falcon_print(const char* s);\n");
    output.push_str("void falcon_print_int(int64_t value);\n");
    output.push_str("void falcon_print_float(double value);\n");
    output.push_str("void falcon_bounds_check(int64_t index, int64_t length);\n");
    output.push_str("void* falcon_alloc(size_t size);\n");
    output.push_str("void falcon_dealloc(void* ptr);\n\n");
    
    // Generate forward declarations for all functions
    output.push_str("/* Function Declarations */\n");
    for closure in &closure_defs {
        output.push_str(&generate_closure_declaration(closure)?);
        output.push_str(";\n");
    }
    for func in &module.functions {
        output.push_str(&generate_function_declaration(func)?);
        output.push_str(";\n");
    }
    output.push_str("\n");

    // Generate closure implementations before regular functions
    if !closure_defs.is_empty() {
        output.push_str("/* Closure Implementations */\n");
        for closure in &closure_defs {
            output.push_str(&generate_closure_definition(closure)?);
            output.push_str("\n");
        }
    }
    
    // Generate function implementations
    for func in &module.functions {
        output.push_str(&ir_function_to_c(func)?);
        output.push_str("\n");
    }
    
    Ok(output)
}

/// Generate a function declaration (signature only)
fn generate_function_declaration(func: &IrFunction) -> Result<String, String> {
    // In C, main() must return int
    let return_type = if func.name == "main" {
        "int".to_string()
    } else {
        match &func.return_type {
            Some(ty) => ir_type_to_c(ty)?,
            None => "void".to_string(),
        }
    };
    
    let mut decl = format!("{} {}(", return_type, func.name);
    
    if func.params.is_empty() {
        decl.push_str("void");
    } else {
        for (i, param) in func.params.iter().enumerate() {
            if i > 0 {
                decl.push_str(", ");
            }
            let param_type = ir_type_to_c(&param.ty)?;
            decl.push_str(&format!("{} {}", param_type, param.name));
        }
    }
    
    decl.push(')');
    Ok(decl)
}

fn closure_function_name(closure_id: usize) -> String {
    format!("__closure_{}", closure_id)
}

fn collect_closure_defs(module: &IrModule) -> Vec<ClosureDef> {
    let mut defs: HashMap<usize, ClosureDef> = HashMap::new();

    for func in &module.functions {
        collect_closure_defs_from_instructions(&func.body.instructions, &mut defs);
    }

    let mut result: Vec<ClosureDef> = defs.into_values().collect();
    result.sort_by_key(|closure| closure.closure_id);
    result
}

fn collect_closure_defs_from_instructions(
    instructions: &[IrInstruction],
    defs: &mut HashMap<usize, ClosureDef>,
) {
    for inst in instructions {
        if let IrInstruction::ClosureCreate { closure_id, params, body, .. } = inst {
            defs.entry(*closure_id).or_insert_with(|| ClosureDef {
                closure_id: *closure_id,
                params: params.clone(),
                body: body.clone(),
            });

            // Nested closures can appear in closure bodies.
            collect_closure_defs_from_instructions(body, defs);
        }
    }
}

fn generate_closure_declaration(closure: &ClosureDef) -> Result<String, String> {
    let mut decl = format!("int64_t {}(", closure_function_name(closure.closure_id));

    if closure.params.is_empty() {
        decl.push_str("void");
    } else {
        for (i, param) in closure.params.iter().enumerate() {
            if i > 0 {
                decl.push_str(", ");
            }
            let param_type = ir_type_to_c(&param.ty)?;
            decl.push_str(&format!("{} {}", param_type, param.name));
        }
    }

    decl.push(')');
    Ok(decl)
}

fn generate_closure_definition(closure: &ClosureDef) -> Result<String, String> {
    let mut ctx = CodegenContext::new();
    let mut output = String::new();

    output.push_str(&generate_closure_declaration(closure)?);
    output.push_str(" {\n");

    // Register parameters
    for param in &closure.params {
        let c_type = ir_type_to_c(&param.ty)?;
        ctx.register_var(param.name.clone(), c_type);
        ctx.declared.insert(param.name.clone());
    }

    // First pass: collect all variables and types
    collect_variable_types(&closure.body, &mut ctx)?;

    let declarations = generate_variable_declarations(&ctx);
    if !declarations.is_empty() {
        output.push_str(&declarations);
        output.push_str("\n");
    }

    // Generate closure body
    let mut has_return = false;
    for inst in &closure.body {
        let inst_code = ir_instruction_to_c(inst, &mut ctx)?;
        if !inst_code.is_empty() {
            output.push_str(&ctx.indent_str());
            output.push_str(&inst_code);
            output.push_str("\n");
            if matches!(inst, IrInstruction::Return { .. }) {
                has_return = true;
            }
        }
    }

    // Closure semantics: return value of the final instruction, fallback to 0.
    if !has_return {
        let return_value = closure.body.last()
            .and_then(instruction_result_value)
            .map(value_to_c)
            .unwrap_or_else(|| "0".to_string());
        output.push_str(&ctx.indent_str());
        output.push_str(&format!("return {};\n", return_value));
    }

    output.push_str("}\n");
    Ok(output)
}

fn instruction_result_value(inst: &IrInstruction) -> Option<&IrValue> {
    match inst {
        IrInstruction::Literal { dest, .. } |
        IrInstruction::Add { dest, .. } |
        IrInstruction::Sub { dest, .. } |
        IrInstruction::Mul { dest, .. } |
        IrInstruction::Div { dest, .. } |
        IrInstruction::Mod { dest, .. } |
        IrInstruction::Eq { dest, .. } |
        IrInstruction::Ne { dest, .. } |
        IrInstruction::Lt { dest, .. } |
        IrInstruction::Le { dest, .. } |
        IrInstruction::Gt { dest, .. } |
        IrInstruction::Ge { dest, .. } |
        IrInstruction::And { dest, .. } |
        IrInstruction::Or { dest, .. } |
        IrInstruction::Not { dest, .. } |
        IrInstruction::BitNot { dest, .. } |
        IrInstruction::Neg { dest, .. } |
        IrInstruction::BitAnd { dest, .. } |
        IrInstruction::BitOr { dest, .. } |
        IrInstruction::BitXor { dest, .. } |
        IrInstruction::Shl { dest, .. } |
        IrInstruction::Shr { dest, .. } |
        IrInstruction::Move { dest, .. } |
        IrInstruction::Copy { dest, .. } |
        IrInstruction::Load { dest, .. } |
        IrInstruction::VolatileLoad { dest, .. } |
        IrInstruction::BorrowImm { dest, .. } |
        IrInstruction::BorrowMut { dest, .. } |
        IrInstruction::Index { dest, .. } |
        IrInstruction::FieldAccess { dest, .. } |
        IrInstruction::StructInit { dest, .. } |
        IrInstruction::ArrayInit { dest, .. } |
        IrInstruction::EnumInit { dest, .. } |
        IrInstruction::EnumTag { dest, .. } |
        IrInstruction::EnumPayload { dest, .. } |
        IrInstruction::Range { dest, .. } |
        IrInstruction::StackAlloc { dest, .. } |
        IrInstruction::HeapAlloc { dest, .. } |
        IrInstruction::Alloc { dest, .. } |
        IrInstruction::Unwrap { dest, .. } |
        IrInstruction::AddrOf { dest, .. } |
        IrInstruction::PtrDeref { dest, .. } => Some(dest),
        IrInstruction::Call { dest, .. } |
        IrInstruction::ClosureCall { dest, .. } => dest.as_ref(),
        _ => None,
    }
}

fn ir_function_to_c(func: &IrFunction) -> Result<String, String> {
    let mut ctx = CodegenContext::new();
    let mut output = String::new();
    
    // Function signature
    output.push_str(&generate_function_declaration(func)?);
    output.push_str(" {\n");
    
    // Register parameters
    for param in &func.params {
        let c_type = ir_type_to_c(&param.ty)?;
        ctx.register_var(param.name.clone(), c_type);
        ctx.declared.insert(param.name.clone());
    }
    
    // First pass: collect all variables and their types
    collect_variable_types(&func.body.instructions, &mut ctx)?;
    
    // Generate variable declarations at the start of the function
    let declarations = generate_variable_declarations(&ctx);
    if !declarations.is_empty() {
        output.push_str(&declarations);
        output.push_str("\n");
    }
    
    // Generate function body
    let mut has_return = false;
    for inst in &func.body.instructions {
        let inst_code = ir_instruction_to_c(inst, &mut ctx)?;
        if !inst_code.is_empty() {
            output.push_str(&ctx.indent_str());
            output.push_str(&inst_code);
            output.push_str("\n");
            if matches!(inst, IrInstruction::Return { .. }) {
                has_return = true;
            }
        }
    }
    
    // For main function, add return 0 if not explicitly returned
    if func.name == "main" && !has_return {
        output.push_str(&ctx.indent_str());
        output.push_str("return 0;\n");
    }
    
    output.push_str("}\n");
    
    Ok(output)
}

/// Collect all variable types from instructions
fn collect_variable_types(instructions: &[IrInstruction], ctx: &mut CodegenContext) -> Result<(), String> {
    for inst in instructions {
        match inst {
            IrInstruction::Literal { value, dest } => {
                let c_type = literal_to_c_type(value);
                register_value_type(dest, &c_type, ctx);
            }
            IrInstruction::Add { dest, .. } |
            IrInstruction::Sub { dest, .. } |
            IrInstruction::Mul { dest, .. } |
            IrInstruction::Div { dest, .. } |
            IrInstruction::Mod { dest, .. } => {
                // Arithmetic operations - assume int32_t for now
                register_value_type(dest, "int32_t", ctx);
            }
            IrInstruction::Eq { dest, .. } |
            IrInstruction::Ne { dest, .. } |
            IrInstruction::Lt { dest, .. } |
            IrInstruction::Le { dest, .. } |
            IrInstruction::Gt { dest, .. } |
            IrInstruction::Ge { dest, .. } |
            IrInstruction::And { dest, .. } |
            IrInstruction::Or { dest, .. } |
            IrInstruction::Not { dest, .. } => {
                register_value_type(dest, "bool", ctx);
            }
            IrInstruction::Neg { dest, .. } |
            IrInstruction::BitNot { dest, .. } => {
                register_value_type(dest, "int32_t", ctx);
            }
            IrInstruction::AddrOf { dest, .. } => {
                register_value_type(dest, "int64_t*", ctx);
            }
            IrInstruction::PtrDeref { dest, .. } => {
                register_value_type(dest, "int64_t", ctx);
            }
            IrInstruction::BitAnd { dest, .. } |
            IrInstruction::BitOr { dest, .. } |
            IrInstruction::BitXor { dest, .. } |
            IrInstruction::Shl { dest, .. } |
            IrInstruction::Shr { dest, .. } => {
                register_value_type(dest, "int32_t", ctx);
            }
            IrInstruction::Call { dest, func, .. } => {
                if let Some(d) = dest {
                    // Determine return type based on function name
                    // Skip void-returning functions - they don't need dest
                    let ret_type = if func == "println" || func == "falcon_println" || func == "print" {
                        // void - don't register
                        continue;
                    } else {
                        "int32_t" // Default assumption
                    };
                    register_value_type(d, ret_type, ctx);
                }
            }
            IrInstruction::ClosureCall { dest, .. } => {
                if let Some(d) = dest {
                    register_value_type(d, "int64_t", ctx);
                }
            }
            IrInstruction::ClosureCreate { closure_id, body: _, dest, .. } => {
                // Track closure identity; value is not emitted as a C scalar.
                let closure_name = closure_function_name(*closure_id);
                let dest_name = value_name(dest);
                ctx.temp_to_closure.insert(dest_name, closure_name);
            }
            IrInstruction::Move { src, dest } => {
                // Track closure assignment chains through Move.
                if let Some(closure_name) = resolve_closure_mapping(ctx, src) {
                    let dest_name = value_name(dest);
                    ctx.closure_functions.insert(dest_name.clone(), closure_name.clone());
                    ctx.temp_to_closure.insert(dest_name, closure_name);
                    continue;
                }
                // Move inherits type from source, default to generic
                register_value_type(dest, "int32_t", ctx);
            }
            IrInstruction::BorrowImm { dest, .. } |
            IrInstruction::BorrowMut { dest, .. } => {
                register_value_type(dest, "void*", ctx);
            }
            IrInstruction::Alloc { dest, ty, .. } |
            IrInstruction::StackAlloc { dest, ty, .. } |
            IrInstruction::HeapAlloc { dest, ty, .. } => {
                let c_type = ir_type_to_c(ty)?;
                register_value_type(dest, &format!("{}*", c_type), ctx);
            }
            IrInstruction::Load { dest, .. } => {
                register_value_type(dest, "int32_t", ctx);
            }
            IrInstruction::VolatileLoad { dest, .. } => {
                register_value_type(dest, "int64_t", ctx);
            }
            IrInstruction::Index { dest, .. } |
            IrInstruction::FieldAccess { dest, .. } => {
                register_value_type(dest, "int32_t", ctx);
            }
            IrInstruction::Copy { dest, .. } => {
                register_value_type(dest, "int32_t", ctx);
            }
            IrInstruction::StructInit { struct_name, dest, .. } => {
                // Register as struct type - use struct name
                register_value_type(dest, &format!("struct {}", struct_name), ctx);
            }
            IrInstruction::ArrayInit { dest, .. } => {
                // Register as array pointer
                register_value_type(dest, "int64_t*", ctx);
            }
            IrInstruction::EnumInit { enum_name, dest, .. } => {
                // Register as enum struct type
                register_value_type(dest, &format!("struct {}", enum_name), ctx);
            }
            IrInstruction::EnumTag { dest, .. } => {
                // Tag is always an integer
                register_value_type(dest, "uint32_t", ctx);
            }
            IrInstruction::EnumPayload { dest, .. } => {
                // Payload type is generic for now
                register_value_type(dest, "int64_t", ctx);
            }
            IrInstruction::TypeHint { name, ty } => {
                // Use the type hint to register the correct C type
                let c_type = ir_type_to_c(ty)?;
                ctx.register_var(name.clone(), c_type);
            }
            _ => {}
        }
    }
    Ok(())
}

fn register_value_type(value: &IrValue, c_type: &str, ctx: &mut CodegenContext) {
    let name = value_name(value);
    ctx.register_var(name, c_type.to_string());
}

fn value_name(value: &IrValue) -> String {
    match value {
        IrValue::Variable(name) => name.clone(),
        IrValue::Temporary(n) => format!("_temp_{}", n),
        IrValue::Constant(_) => String::new(),
    }
}

fn resolve_closure_mapping(ctx: &CodegenContext, value: &IrValue) -> Option<String> {
    let name = value_name(value);
    if let Some(closure_name) = ctx.closure_functions.get(&name) {
        return Some(closure_name.clone());
    }
    if let Some(closure_name) = ctx.temp_to_closure.get(&name) {
        return Some(closure_name.clone());
    }
    None
}

fn map_runtime_function_name(func: &str) -> String {
    match func {
        "println" => "falcon_println".to_string(),
        "print" => "falcon_print".to_string(),
        "print_int" => "falcon_print_int".to_string(),
        "print_float" => "falcon_print_float".to_string(),
        _ => func.to_string(),
    }
}

fn is_void_c_function(func: &str) -> bool {
    matches!(func, "falcon_println" | "falcon_print" | "falcon_print_int" | "falcon_print_float" | "printf")
}

fn literal_to_c_type(lit: &IrLiteral) -> String {
    match lit {
        IrLiteral::Int(_) => "int64_t".to_string(),
        IrLiteral::Float(_) => "double".to_string(),
        IrLiteral::Bool(_) => "bool".to_string(),
        IrLiteral::String(_) => "const char*".to_string(),
        IrLiteral::Char(_) => "char".to_string(),
    }
}

/// Generate variable declarations for all collected variables
fn generate_variable_declarations(ctx: &CodegenContext) -> String {
    let mut output = String::new();
    let mut sorted_vars: Vec<_> = ctx.var_types.iter()
        .filter(|(name, c_type)| {
            !ctx.declared.contains(*name) && 
            !name.is_empty() && 
            *c_type != "void" && // Don't declare void variables
            !ctx.closure_functions.contains_key(*name) &&
            !ctx.temp_to_closure.contains_key(*name)
        })
        .collect();
    sorted_vars.sort_by(|a, b| a.0.cmp(b.0));
    
    for (name, c_type) in sorted_vars {
        output.push_str(&format!("    {} {};\n", c_type, name));
    }
    
    output
}

fn ir_instruction_to_c(inst: &IrInstruction, ctx: &mut CodegenContext) -> Result<String, String> {
    match inst {
        IrInstruction::Literal { value, dest } => {
            let c_value = literal_to_c(value);
            let var_name = value_to_c(dest);
            Ok(format!("{} = {};", var_name, c_value))
        }
        IrInstruction::Add { left, right, dest } => {
            Ok(format!("{} = {} + {};", value_to_c(dest), value_to_c(left), value_to_c(right)))
        }
        IrInstruction::Sub { left, right, dest } => {
            Ok(format!("{} = {} - {};", value_to_c(dest), value_to_c(left), value_to_c(right)))
        }
        IrInstruction::Mul { left, right, dest } => {
            Ok(format!("{} = {} * {};", value_to_c(dest), value_to_c(left), value_to_c(right)))
        }
        IrInstruction::Div { left, right, dest } => {
            Ok(format!("{} = {} / {};", value_to_c(dest), value_to_c(left), value_to_c(right)))
        }
        IrInstruction::Mod { left, right, dest } => {
            Ok(format!("{} = {} % {};", value_to_c(dest), value_to_c(left), value_to_c(right)))
        }
        IrInstruction::Eq { left, right, dest } => {
            Ok(format!("{} = {} == {};", value_to_c(dest), value_to_c(left), value_to_c(right)))
        }
        IrInstruction::Ne { left, right, dest } => {
            Ok(format!("{} = {} != {};", value_to_c(dest), value_to_c(left), value_to_c(right)))
        }
        IrInstruction::Lt { left, right, dest } => {
            Ok(format!("{} = {} < {};", value_to_c(dest), value_to_c(left), value_to_c(right)))
        }
        IrInstruction::Le { left, right, dest } => {
            Ok(format!("{} = {} <= {};", value_to_c(dest), value_to_c(left), value_to_c(right)))
        }
        IrInstruction::Gt { left, right, dest } => {
            Ok(format!("{} = {} > {};", value_to_c(dest), value_to_c(left), value_to_c(right)))
        }
        IrInstruction::Ge { left, right, dest } => {
            Ok(format!("{} = {} >= {};", value_to_c(dest), value_to_c(left), value_to_c(right)))
        }
        IrInstruction::And { left, right, dest } => {
            Ok(format!("{} = {} && {};", value_to_c(dest), value_to_c(left), value_to_c(right)))
        }
        IrInstruction::Or { left, right, dest } => {
            Ok(format!("{} = {} || {};", value_to_c(dest), value_to_c(left), value_to_c(right)))
        }
        IrInstruction::Not { operand, dest } => {
            Ok(format!("{} = !{};", value_to_c(dest), value_to_c(operand)))
        }
        IrInstruction::Neg { operand, dest } => {
            Ok(format!("{} = -{};", value_to_c(dest), value_to_c(operand)))
        }
        IrInstruction::BitNot { operand, dest } => {
            Ok(format!("{} = ~{};", value_to_c(dest), value_to_c(operand)))
        }
        IrInstruction::AddrOf { operand, dest } => {
            Ok(format!("{} = &{};", value_to_c(dest), value_to_c(operand)))
        }
        IrInstruction::PtrDeref { operand, dest } => {
            Ok(format!("{} = *((int64_t*){}); /* deref */", value_to_c(dest), value_to_c(operand)))
        }
        IrInstruction::BitAnd { left, right, dest } => {
            Ok(format!("{} = {} & {};", value_to_c(dest), value_to_c(left), value_to_c(right)))
        }
        IrInstruction::BitOr { left, right, dest } => {
            Ok(format!("{} = {} | {};", value_to_c(dest), value_to_c(left), value_to_c(right)))
        }
        IrInstruction::BitXor { left, right, dest } => {
            Ok(format!("{} = {} ^ {};", value_to_c(dest), value_to_c(left), value_to_c(right)))
        }
        IrInstruction::Shl { left, right, dest } => {
            Ok(format!("{} = {} << {};", value_to_c(dest), value_to_c(left), value_to_c(right)))
        }
        IrInstruction::Shr { left, right, dest } => {
            Ok(format!("{} = {} >> {};", value_to_c(dest), value_to_c(left), value_to_c(right)))
        }
        IrInstruction::Call { func, args, dest } => {
            // Resolve closure-backed call first, then runtime mapping.
            let c_func = if let Some(closure_fn) = ctx.closure_functions.get(func) {
                closure_fn.clone()
            } else {
                map_runtime_function_name(func)
            };
            
            // Check if function returns void
            let is_void_func = is_void_c_function(&c_func);
            
            let mut call_str = format!("{}(", c_func);
            for (i, arg) in args.iter().enumerate() {
                if i > 0 {
                    call_str.push_str(", ");
                }
                call_str.push_str(&value_to_c(arg));
            }
            call_str.push(')');
            
            // Don't assign to dest if function returns void
            if !is_void_func {
                if let Some(dest_val) = dest {
                    let dest_var = value_to_c(dest_val);
                    return Ok(format!("{} = {};", dest_var, call_str));
                }
            }
            Ok(format!("{};", call_str))
        }
        IrInstruction::Return { value } => {
            if let Some(val) = value {
                Ok(format!("return {};", value_to_c(val)))
            } else {
                Ok("return;".to_string())
            }
        }
        IrInstruction::Move { src, dest } => {
            if let Some(closure_fn) = resolve_closure_mapping(ctx, src) {
                let dest_name = value_name(dest);
                ctx.closure_functions.insert(dest_name.clone(), closure_fn.clone());
                ctx.temp_to_closure.insert(dest_name.clone(), closure_fn.clone());
                Ok(format!("/* closure bind {} -> {} */", dest_name, closure_fn))
            } else {
                Ok(format!("{} = {};", value_to_c(dest), value_to_c(src)))
            }
        }
        IrInstruction::Copy { src, dest } => {
            Ok(format!("{} = {};", value_to_c(dest), value_to_c(src)))
        }
        IrInstruction::Label { name } => {
            Ok(format!("{}:", name))
        }
        IrInstruction::Branch { label } => {
            Ok(format!("goto {};", label))
        }
        IrInstruction::BranchCond { condition, true_label, false_label } => {
            Ok(format!("if ({}) goto {}; else goto {};", 
                value_to_c(condition), true_label, false_label))
        }
        IrInstruction::Alloc { ty, size, dest } => {
            let c_type = ir_type_to_c(ty)?;
            Ok(format!("{} = ({} *)falcon_alloc(sizeof({}) * {});", 
                value_to_c(dest), c_type, c_type, size))
        }
        IrInstruction::HeapAlloc { ty, size, dest } => {
            let c_type = ir_type_to_c(ty)?;
            Ok(format!("{} = ({} *)falcon_alloc(sizeof({}) * {});", 
                value_to_c(dest), c_type, c_type, size))
        }
        IrInstruction::StackAlloc { ty, size, dest } => {
            let c_type = ir_type_to_c(ty)?;
            // Stack allocation in C - use array
            Ok(format!("{} {}[{}]; {} = {};", 
                c_type, value_to_c(dest), size, value_to_c(dest), value_to_c(dest)))
        }
        IrInstruction::Free { addr } => {
            Ok(format!("falcon_dealloc({});", value_to_c(addr)))
        }
        IrInstruction::Load { addr, dest } => {
            Ok(format!("{} = *{};", value_to_c(dest), value_to_c(addr)))
        }
        IrInstruction::Store { addr, value } => {
            Ok(format!("*{} = {};", value_to_c(addr), value_to_c(value)))
        }
        IrInstruction::VolatileLoad { addr, dest } => {
            Ok(format!(
                "{} = *(volatile int64_t*)(uintptr_t)({});",
                value_to_c(dest),
                value_to_c(addr)
            ))
        }
        IrInstruction::VolatileStore { addr, value } => {
            Ok(format!(
                "*(volatile int64_t*)(uintptr_t)({}) = {};",
                value_to_c(addr),
                value_to_c(value)
            ))
        }
        IrInstruction::Drop { value } => {
            // Drop - typically a no-op for primitives, but we can add cleanup
            Ok(format!("/* drop {} */", value_to_c(value)))
        }
        IrInstruction::BorrowImm { src, dest, .. } => {
            Ok(format!("{} = &{};", value_to_c(dest), value_to_c(src)))
        }
        IrInstruction::BorrowMut { src, dest, .. } => {
            Ok(format!("{} = &{};", value_to_c(dest), value_to_c(src)))
        }
        IrInstruction::Index { base, index, dest } => {
            Ok(format!("{} = {}[{}];", value_to_c(dest), value_to_c(base), value_to_c(index)))
        }
        IrInstruction::FieldAccess { base, field, dest } => {
            Ok(format!("{} = {}.{};", value_to_c(dest), value_to_c(base), field))
        }
        IrInstruction::Panic { message } => {
            Ok(format!("falcon_panic(\"{}\");", message.replace('"', "\\\"")))
        }
        IrInstruction::Unwrap { value, dest, message } => {
            let msg = message.as_ref().map(|m| m.as_str()).unwrap_or("unwrap failed");
            Ok(format!("if ({} == NULL) falcon_panic(\"{}\"); {} = *{};", 
                value_to_c(value), msg, value_to_c(dest), value_to_c(value)))
        }
        IrInstruction::BoundsCheck { value, bound, on_fail: _ } => {
            Ok(format!(
                "falcon_bounds_check({}, {});",
                value_to_c(value),
                value_to_c(bound)
            ))
        }
        IrInstruction::Range { start: _, end: _, dest } => {
            // C backend doesn't support ranges yet, just declare valid variable
            Ok(format!("/* Range not supported in C backend */ {} = 0;", value_to_c(dest)))
        }
        IrInstruction::StructInit { struct_name, fields, dest } => {
            // Generate struct initialization in C
            let dest_name = value_to_c(dest);
            let mut code = format!("/* init {} */", struct_name);
            for (field_name, field_val) in fields {
                code.push_str(&format!(" {}.{} = {};", dest_name, field_name, value_to_c(field_val)));
            }
            Ok(code)
        }
        IrInstruction::ArrayInit { elements, dest } => {
            // Generate array initialization in C
            let dest_name = value_to_c(dest);
            let mut code = format!("int64_t {}_data[] = {{", dest_name);
            for (i, elem) in elements.iter().enumerate() {
                if i > 0 {
                    code.push_str(", ");
                }
                code.push_str(&value_to_c(elem));
            }
            code.push_str("}; ");
            code.push_str(&format!("{} = {}_data;", dest_name, dest_name));
            Ok(code)
        }
        IrInstruction::EnumInit { enum_name, variant, payload, dest } => {
            // Generate enum initialization as tagged union
            // For now, generate as struct with tag and data
            let dest_name = value_to_c(dest);
            if let Some(payload_val) = payload {
                Ok(format!("/* EnumInit {0}::{1} */ {2}.tag = /* {1} tag */0; {2}.data = {3};", 
                    enum_name, variant, dest_name, value_to_c(payload_val)))
            } else {
                Ok(format!("/* EnumInit {0}::{1} */ {2}.tag = /* {1} tag */0;", 
                    enum_name, variant, dest_name))
            }
        }
        IrInstruction::EnumTag { value, dest } => {
            // Extract discriminant from enum
            Ok(format!("{} = {}.tag;", value_to_c(dest), value_to_c(value)))
        }
        IrInstruction::EnumPayload { value, variant, dest } => {
            // Extract payload from enum variant
            Ok(format!("/* EnumPayload {} */ {} = {}.data;", variant, value_to_c(dest), value_to_c(value)))
        }
        IrInstruction::ClosureCreate { closure_id, params: _, body: _, captures: _, dest } => {
            let closure_fn = closure_function_name(*closure_id);
            let dest_name = value_name(dest);
            ctx.temp_to_closure.insert(dest_name.clone(), closure_fn.clone());
            Ok(format!("/* closure create {} -> {} */", dest_name, closure_fn))
        }
        IrInstruction::ClosureCall { closure, args, dest } => {
            let closure_fn = resolve_closure_mapping(ctx, closure)
                .ok_or_else(|| format!("Closure call target has no mapping: {:?}", closure))?;
            let args_str: Vec<String> = args.iter().map(value_to_c).collect();
            let call_expr = format!("{}({})", closure_fn, args_str.join(", "));
            if let Some(d) = dest {
                Ok(format!("{} = {};", value_to_c(d), call_expr))
            } else {
                Ok(format!("{};", call_expr))
            }
        }
        IrInstruction::Cast { operand, target_type, dest } => {
            let c_type = ir_type_to_c(target_type)?;
            Ok(format!("{} = ({})({});", value_to_c(dest), c_type, value_to_c(operand)))
        }
        IrInstruction::TypeHint { .. } => {
            // Type hints are metadata only — no C code emitted
            Ok(String::new())
        }
    }
}

fn value_to_c(value: &IrValue) -> String {
    match value {
        IrValue::Variable(name) => name.clone(),
        IrValue::Temporary(n) => format!("_temp_{}", n),
        IrValue::Constant(lit) => literal_to_c(lit),
    }
}

fn literal_to_c(lit: &IrLiteral) -> String {
    match lit {
        IrLiteral::Int(n) => format!("{}LL", n),
        IrLiteral::Float(f) => {
            if f.is_nan() {
                "NAN".to_string()
            } else if f.is_infinite() {
                if *f > 0.0 { "INFINITY".to_string() } else { "-INFINITY".to_string() }
            } else {
                format!("{}", f)
            }
        }
        IrLiteral::Bool(b) => if *b { "true".to_string() } else { "false".to_string() },
        IrLiteral::String(s) => format!("\"{}\"", s.replace('\\', "\\\\").replace('"', "\\\"").replace('\n', "\\n").replace('\r', "\\r").replace('\t', "\\t")),
        IrLiteral::Char(c) => format!("'{}'", c),
    }
}

fn ir_type_to_c(ty: &IrType) -> Result<String, String> {
    match ty {
        IrType::Int(int_ty) => {
            match int_ty {
                IntType::I8 => Ok("int8_t".to_string()),
                IntType::I16 => Ok("int16_t".to_string()),
                IntType::I32 => Ok("int32_t".to_string()),
                IntType::I64 => Ok("int64_t".to_string()),
                IntType::I128 => Ok("__int128".to_string()),
                IntType::U8 => Ok("uint8_t".to_string()),
                IntType::U16 => Ok("uint16_t".to_string()),
                IntType::U32 => Ok("uint32_t".to_string()),
                IntType::U64 => Ok("uint64_t".to_string()),
                IntType::U128 => Ok("unsigned __int128".to_string()),
                IntType::ISize => Ok("intptr_t".to_string()),
                IntType::USize => Ok("size_t".to_string()),
            }
        }
        IrType::Float(float_ty) => {
            match float_ty {
                FloatType::F32 => Ok("float".to_string()),
                FloatType::F64 => Ok("double".to_string()),
            }
        }
        IrType::Bool => Ok("bool".to_string()),
        IrType::String => Ok("char*".to_string()),
        IrType::Str => Ok("const char*".to_string()),
        IrType::Unit => Ok("void".to_string()),
        IrType::Named(name) => Ok(name.clone()),
        IrType::Pointer { mutable, inner } => {
            let inner_type = ir_type_to_c(inner)?;
            if *mutable {
                Ok(format!("{}*", inner_type))
            } else {
                Ok(format!("const {}*", inner_type))
            }
        }
        IrType::Reference { mutable, inner, .. } => {
            let inner_type = ir_type_to_c(inner)?;
            if *mutable {
                Ok(format!("{}*", inner_type))
            } else {
                Ok(format!("const {}*", inner_type))
            }
        }
        IrType::Array { inner, size } => {
            let inner_type = ir_type_to_c(inner)?;
            if let Some(s) = size {
                Ok(format!("{}[{}]", inner_type, s))
            } else {
                Ok(format!("{}*", inner_type))
            }
        }
        IrType::Tuple(types) => {
            // Tuples become structs in C
            if types.is_empty() {
                Ok("void".to_string())
            } else {
                Ok("struct { /* tuple */ }".to_string())
            }
        }
        IrType::Function { params, return_type } => {
            let ret = ir_type_to_c(return_type)?;
            let params_str: Result<Vec<String>, String> = params.iter().map(ir_type_to_c).collect();
            Ok(format!("{} (*)({})", ret, params_str?.join(", ")))
        }
    }
}
