/* Generated by Falcon Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Falcon Runtime Declarations */
void falcon_panic(const char* msg);
void falcon_println(const char* s);
void falcon_print(const char* s);
void falcon_print_int(int64_t value);
void falcon_print_float(double value);
void* falcon_alloc(size_t size);
void falcon_dealloc(void* ptr);

/* Function Declarations */
int main(void);

int main(void) {
    int64_t* _temp_0;
    int32_t _temp_1;
    int32_t _temp_10;
    const char* _temp_11;
    int32_t _temp_2;
    const char* _temp_3;
    int32_t _temp_5;
    int32_t _temp_6;
    const char* _temp_7;
    int32_t _temp_9;
    int32_t arr;

    int64_t _temp_0_data[] = {10LL, 20LL, 30LL}; _temp_0 = _temp_0_data;
    arr = _temp_0;
    _temp_1 = arr[0LL];
    falcon_print_int(_temp_1);
    _temp_3 = " ";
    falcon_print(_temp_3);
    _temp_5 = arr[1LL];
    falcon_print_int(_temp_5);
    _temp_7 = " ";
    falcon_print(_temp_7);
    _temp_9 = arr[2LL];
    falcon_print_int(_temp_9);
    _temp_11 = "";
    falcon_println(_temp_11);
    return 0;
}

