/* Generated by Falcon Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Falcon Runtime Declarations */
void falcon_panic(const char* msg);
void falcon_println(const char* s);
void falcon_print(const char* s);
void falcon_print_int(int64_t value);
void falcon_print_float(double value);
void* falcon_alloc(size_t size);
void falcon_dealloc(void* ptr);

/* Function Declarations */
int64_t __closure_0(void);
int64_t __closure_1(int64_t x);
int64_t __closure_2(int64_t x);
int64_t __closure_3(int64_t a, int64_t b);
int64_t __closure_4(int64_t x, int64_t y);
int64_t __closure_5(int64_t n);
int main(void);

/* Closure Implementations */
int64_t __closure_0(void) {
    int64_t _temp_0;

    _temp_0 = 100LL;
    return _temp_0;
}

int64_t __closure_1(int64_t x) {
    int32_t _temp_4;

    _temp_4 = x;
    return _temp_4;
}

int64_t __closure_2(int64_t x) {
    int32_t _temp_10;
    int64_t _temp_9;

    _temp_9 = 2LL;
    _temp_10 = x * _temp_9;
    return _temp_10;
}

int64_t __closure_3(int64_t a, int64_t b) {
    int32_t _temp_15;

    _temp_15 = a + b;
    return _temp_15;
}

int64_t __closure_4(int64_t x, int64_t y) {
    int32_t _temp_21;

    _temp_21 = x * y;
    return _temp_21;
}

int64_t __closure_5(int64_t n) {
    int64_t _temp_27;
    int32_t _temp_28;

    _temp_27 = 10LL;
    _temp_28 = n + _temp_27;
    return _temp_28;
}

int main(void) {
    int64_t _temp_12;
    int64_t _temp_13;
    int32_t _temp_14;
    int64_t _temp_17;
    int64_t _temp_18;
    int64_t _temp_19;
    int64_t _temp_2;
    int32_t _temp_20;
    int64_t _temp_23;
    int64_t _temp_24;
    int64_t _temp_25;
    int32_t _temp_26;
    int32_t _temp_3;
    int64_t _temp_30;
    int64_t _temp_31;
    int32_t _temp_32;
    int64_t _temp_33;
    int64_t _temp_34;
    int64_t _temp_35;
    int32_t _temp_36;
    int64_t _temp_37;
    int32_t _temp_38;
    int64_t _temp_6;
    int64_t _temp_7;
    int32_t _temp_8;
    int32_t composed;
    int32_t val1;
    int32_t val2;
    int32_t val3;
    int32_t val4;
    int32_t val5;
    int32_t val6;

    /* closure create _temp_1 -> __closure_0 */
    /* closure bind get_val -> __closure_0 */
    _temp_2 = __closure_0();
    val1 = _temp_2;
    falcon_print_int(val1);
    /* closure create _temp_5 -> __closure_1 */
    /* closure bind identity -> __closure_1 */
    _temp_6 = 42LL;
    _temp_7 = __closure_1(_temp_6);
    val2 = _temp_7;
    falcon_print_int(val2);
    /* closure create _temp_11 -> __closure_2 */
    /* closure bind double -> __closure_2 */
    _temp_12 = 25LL;
    _temp_13 = __closure_2(_temp_12);
    val3 = _temp_13;
    falcon_print_int(val3);
    /* closure create _temp_16 -> __closure_3 */
    /* closure bind add -> __closure_3 */
    _temp_17 = 10LL;
    _temp_18 = 20LL;
    _temp_19 = __closure_3(_temp_17, _temp_18);
    val4 = _temp_19;
    falcon_print_int(val4);
    /* closure create _temp_22 -> __closure_4 */
    /* closure bind multiply -> __closure_4 */
    _temp_23 = 6LL;
    _temp_24 = 7LL;
    _temp_25 = __closure_4(_temp_23, _temp_24);
    val5 = _temp_25;
    falcon_print_int(val5);
    /* closure create _temp_29 -> __closure_5 */
    /* closure bind add_ten -> __closure_5 */
    _temp_30 = 90LL;
    _temp_31 = __closure_5(_temp_30);
    val6 = _temp_31;
    falcon_print_int(val6);
    _temp_33 = 5LL;
    _temp_34 = __closure_2(_temp_33);
    _temp_35 = __closure_5(_temp_34);
    composed = _temp_35;
    falcon_print_int(composed);
    _temp_37 = 999LL;
    falcon_print_int(_temp_37);
    return 0;
}

