/* Generated by Falcon Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Falcon Runtime Declarations */
void falcon_panic(const char* msg);
void falcon_println(const char* s);
void falcon_print(const char* s);
void falcon_print_int(int64_t value);
void falcon_print_float(double value);
void* falcon_alloc(size_t size);
void falcon_dealloc(void* ptr);

/* Function Declarations */
int main(void);

int main(void) {
    int64_t _temp_0;
    int64_t _temp_1;
    const char* _temp_10;
    int32_t _temp_12;
    const char* _temp_13;
    int64_t _temp_15;
    int32_t _temp_16;
    const char* _temp_17;
    int32_t _temp_19;
    int32_t _temp_2;
    const char* _temp_20;
    int64_t _temp_22;
    int32_t _temp_23;
    const char* _temp_24;
    int32_t _temp_26;
    const char* _temp_27;
    const char* _temp_3;
    int32_t _temp_5;
    const char* _temp_6;
    int64_t _temp_8;
    int32_t _temp_9;
    int32_t x;

    _temp_0 = 10LL;
    x = _temp_0;
    _temp_1 = 5LL;
    _temp_2 = x + _temp_1;
    x = _temp_2;
    _temp_3 = "After += 5: ";
    falcon_print(_temp_3);
    falcon_print_int(x);
    _temp_6 = "";
    falcon_println(_temp_6);
    _temp_8 = 3LL;
    _temp_9 = x - _temp_8;
    x = _temp_9;
    _temp_10 = "After -= 3: ";
    falcon_print(_temp_10);
    falcon_print_int(x);
    _temp_13 = "";
    falcon_println(_temp_13);
    _temp_15 = 2LL;
    _temp_16 = x * _temp_15;
    x = _temp_16;
    _temp_17 = "After *= 2: ";
    falcon_print(_temp_17);
    falcon_print_int(x);
    _temp_20 = "";
    falcon_println(_temp_20);
    _temp_22 = 4LL;
    _temp_23 = x / _temp_22;
    x = _temp_23;
    _temp_24 = "After /= 4: ";
    falcon_print(_temp_24);
    falcon_print_int(x);
    _temp_27 = "";
    falcon_println(_temp_27);
    return 0;
}

