/* Generated by Falcon Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Falcon Runtime Declarations */
void falcon_panic(const char* msg);
void falcon_println(const char* s);
void falcon_print(const char* s);
void falcon_print_int(int64_t value);
void falcon_print_float(double value);
void* falcon_alloc(size_t size);
void falcon_dealloc(void* ptr);

/* Function Declarations */
int main(void);

int main(void) {
    const char* _temp_0;
    int32_t _temp_11;
    int32_t _temp_12;
    const char* _temp_13;
    int32_t _temp_15;
    int32_t _temp_16;
    const char* _temp_17;
    const char* _temp_19;
    const char* _temp_2;
    const char* _temp_21;
    const char* _temp_23;
    int64_t _temp_25;
    int64_t _temp_26;
    bool _temp_27;
    int32_t _temp_28;
    int32_t _temp_29;
    const char* _temp_30;
    int64_t _temp_32;
    int32_t _temp_33;
    const char* _temp_34;
    const char* _temp_36;
    const char* _temp_38;
    const char* _temp_4;
    const char* _temp_40;
    int64_t _temp_42;
    int64_t _temp_43;
    int32_t _temp_44;
    int32_t _temp_45;
    const char* _temp_46;
    const char* _temp_48;
    int64_t _temp_50;
    int64_t _temp_51;
    int32_t _temp_52;
    int32_t _temp_53;
    const char* _temp_54;
    const char* _temp_56;
    const char* _temp_58;
    int64_t _temp_6;
    int64_t _temp_7;
    struct Point _temp_8;
    const char* _temp_9;
    int32_t i;
    int32_t p;

    _temp_0 = "=== Falcon Demo ===";
    falcon_println(_temp_0);
    _temp_2 = "";
    falcon_println(_temp_2);
    _temp_4 = "1. Struct with fields:";
    falcon_println(_temp_4);
    _temp_6 = 100LL;
    _temp_7 = 200LL;
    /* init Point */ _temp_8.x = _temp_6; _temp_8.y = _temp_7;
    p = _temp_8;
    _temp_9 = "   x = ";
    falcon_print(_temp_9);
    _temp_11 = p.x;
    falcon_print_int(_temp_11);
    _temp_13 = ", y = ";
    falcon_print(_temp_13);
    _temp_15 = p.y;
    falcon_print_int(_temp_15);
    _temp_17 = "";
    falcon_println(_temp_17);
    _temp_19 = "";
    falcon_println(_temp_19);
    _temp_21 = "2. For loop - squares:";
    falcon_println(_temp_21);
    _temp_23 = "   ";
    falcon_print(_temp_23);
    _temp_25 = 1LL;
    i = _temp_25;
    _temp_26 = 11LL;
    for_start_25:
    _temp_27 = i < _temp_26;
    if (_temp_27) goto for_body_25; else goto for_end_25;
    for_body_25:
    _temp_28 = i * i;
    falcon_print_int(_temp_28);
    _temp_30 = " ";
    falcon_print(_temp_30);
    _temp_32 = 1LL;
    _temp_33 = i + _temp_32;
    i = _temp_33;
    goto for_start_25;
    for_end_25:
    _temp_34 = "";
    falcon_println(_temp_34);
    _temp_36 = "";
    falcon_println(_temp_36);
    _temp_38 = "3. Arithmetic:";
    falcon_println(_temp_38);
    _temp_40 = "   5 + 3 = ";
    falcon_print(_temp_40);
    _temp_42 = 5LL;
    _temp_43 = 3LL;
    _temp_44 = _temp_42 + _temp_43;
    falcon_print_int(_temp_44);
    _temp_46 = "";
    falcon_println(_temp_46);
    _temp_48 = "   10 * 7 = ";
    falcon_print(_temp_48);
    _temp_50 = 10LL;
    _temp_51 = 7LL;
    _temp_52 = _temp_50 * _temp_51;
    falcon_print_int(_temp_52);
    _temp_54 = "";
    falcon_println(_temp_54);
    _temp_56 = "";
    falcon_println(_temp_56);
    _temp_58 = "=== Demo Complete ===";
    falcon_println(_temp_58);
    return 0;
}

