/* Generated by Falcon Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Falcon Runtime Declarations */
void falcon_panic(const char* msg);
void falcon_println(const char* s);
void falcon_print(const char* s);
void falcon_print_int(int64_t value);
void falcon_print_float(double value);
void* falcon_alloc(size_t size);
void falcon_dealloc(void* ptr);

/* Function Declarations */
int32_t double_value(int32_t x);
int main(void);

int32_t double_value(int32_t x) {
    int32_t _temp_0;

    _temp_0 = x + x;
    return _temp_0;
}

int main(void) {
    int64_t _temp_0;
    int32_t _temp_1;
    const char* _temp_2;
    int32_t _temp_4;
    const char* _temp_5;
    int32_t a;
    int32_t b;

    _temp_0 = 5LL;
    a = _temp_0;
    _temp_1 = double_value(a);
    b = _temp_1;
    _temp_2 = "Doubled value: ";
    falcon_print(_temp_2);
    falcon_print_int(b);
    _temp_5 = "";
    falcon_println(_temp_5);
    return 0;
}

