/* Generated by Falcon Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Falcon Runtime Declarations */
void falcon_panic(const char* msg);
void falcon_println(const char* s);
void falcon_print(const char* s);
void falcon_print_int(int64_t value);
void falcon_print_float(double value);
void* falcon_alloc(size_t size);
void falcon_dealloc(void* ptr);

/* Function Declarations */
int main(void);

int main(void) {
    struct Status _temp_0;
    uint32_t _temp_10;
    const char* _temp_12;
    int32_t _temp_14;
    int32_t _temp_15;
    int64_t _temp_16;
    int32_t _temp_18;
    struct Status _temp_2;
    struct Status _temp_4;
    struct Status _temp_6;
    uint32_t _temp_8;
    int32_t p4;
    int32_t s1;
    int32_t s2;
    int32_t s3;
    int32_t s4;
    int32_t t1;
    int32_t t4;

    /* EnumInit Status::Pending */ _temp_0.tag = /* Pending tag */0;
    s1 = _temp_1;
    /* EnumInit Status::Running */ _temp_2.tag = /* Running tag */0;
    s2 = _temp_3;
    /* EnumInit Status::Done */ _temp_4.tag = /* Done tag */0;
    s3 = _temp_5;
    /* EnumInit Status::Failed */ _temp_6.tag = /* Failed tag */0; _temp_6.data = 42LL;
    s4 = _temp_7;
    _temp_8 = s1.tag;
    t1 = _temp_9;
    _temp_10 = s4.tag;
    t4 = _temp_11;
    _temp_12 = "Status enum tags:";
    falcon_println(_temp_12);
    _temp_14 = print_i32(t1);
    _temp_15 = print_i32(t4);
    /* EnumPayload  */ _temp_16 = s4.data;
    p4 = _temp_17;
    _temp_18 = print_i32(p4);
    return 0;
}

