/* Generated by Falcon Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Falcon Runtime Declarations */
void falcon_panic(const char* msg);
void falcon_println(const char* s);
void falcon_print(const char* s);
void falcon_print_int(int64_t value);
void falcon_print_float(double value);
void* falcon_alloc(size_t size);
void falcon_dealloc(void* ptr);

/* Function Declarations */
int main(void);

int main(void) {
    struct Option _temp_0;
    const char* _temp_11;
    int32_t _temp_13;
    const char* _temp_14;
    struct Option _temp_16;
    uint32_t _temp_18;
    uint32_t _temp_2;
    const char* _temp_20;
    int32_t _temp_22;
    const char* _temp_23;
    const char* _temp_4;
    int32_t _temp_6;
    const char* _temp_7;
    int64_t _temp_9;
    int32_t none_opt;
    int32_t opt;
    int32_t p;
    int32_t t;
    int32_t t2;

    /* EnumInit Option::Some */ _temp_0.tag = /* Some tag */0; _temp_0.data = 42LL;
    opt = _temp_1;
    _temp_2 = opt.tag;
    t = _temp_3;
    _temp_4 = "Tag: ";
    falcon_print(_temp_4);
    falcon_print_int(t);
    _temp_7 = "";
    falcon_println(_temp_7);
    /* EnumPayload  */ _temp_9 = opt.data;
    p = _temp_10;
    _temp_11 = "Payload: ";
    falcon_print(_temp_11);
    falcon_print_int(p);
    _temp_14 = "";
    falcon_println(_temp_14);
    /* EnumInit Option::None */ _temp_16.tag = /* None tag */0;
    none_opt = _temp_17;
    _temp_18 = none_opt.tag;
    t2 = _temp_19;
    _temp_20 = "None tag: ";
    falcon_print(_temp_20);
    falcon_print_int(t2);
    _temp_23 = "";
    falcon_println(_temp_23);
    return 0;
}

