/* Generated by Falcon Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Falcon Runtime Declarations */
void falcon_panic(const char* msg);
void falcon_println(const char* s);
void falcon_print(const char* s);
void falcon_print_int(int64_t value);
void falcon_print_float(double value);
void* falcon_alloc(size_t size);
void falcon_dealloc(void* ptr);

/* Function Declarations */
int main(void);

int main(void) {
    int64_t _temp_0;
    int32_t x;

    _temp_0 = 1LL;
    x = _temp_0;
    falcon_println(x);
    return 0;
}

