/* Generated by Falcon Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Falcon Runtime Declarations */
void falcon_panic(const char* msg);
void falcon_println(const char* s);
void falcon_print(const char* s);
void falcon_print_int(int64_t value);
void falcon_print_float(double value);
void* falcon_alloc(size_t size);
void falcon_dealloc(void* ptr);

/* Function Declarations */
int main(void);

int main(void) {
    int64_t _temp_0;
    int64_t _temp_10;
    bool _temp_11;
    const char* _temp_12;
    const char* _temp_14;
    int64_t _temp_2;
    bool _temp_3;
    const char* _temp_4;
    int64_t _temp_6;
    bool _temp_7;
    const char* _temp_8;
    int32_t status;

    _temp_0 = 1LL;
    status = _temp_0;
    _temp_2 = 0LL;
    _temp_3 = status == _temp_2;
    if (_temp_3) goto match_body_1_0; else goto match_check_1_1;
    match_body_1_0:
    _temp_4 = "Pending";
    falcon_println(_temp_4);
    goto match_end_1;
    match_check_1_1:
    _temp_6 = 1LL;
    _temp_7 = status == _temp_6;
    if (_temp_7) goto match_body_1_1; else goto match_check_1_2;
    match_body_1_1:
    _temp_8 = "Running";
    falcon_println(_temp_8);
    goto match_end_1;
    match_check_1_2:
    _temp_10 = 2LL;
    _temp_11 = status == _temp_10;
    if (_temp_11) goto match_body_1_2; else goto match_check_1_3;
    match_body_1_2:
    _temp_12 = "Done";
    falcon_println(_temp_12);
    goto match_end_1;
    match_check_1_3:
    match_body_1_3:
    _temp_14 = "Unknown";
    falcon_println(_temp_14);
    goto match_end_1;
    match_end_1:
    return 0;
}

