/* Generated by Falcon Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Falcon Runtime Declarations */
void falcon_panic(const char* msg);
void falcon_println(const char* s);
void falcon_print(const char* s);
void falcon_print_int(int64_t value);
void falcon_print_float(double value);
void* falcon_alloc(size_t size);
void falcon_dealloc(void* ptr);

/* Function Declarations */
int32_t factorial(int32_t n);
int main(void);

int32_t factorial(int32_t n) {
    int64_t _temp_0;
    bool _temp_1;
    int64_t _temp_2;
    int64_t _temp_3;
    int32_t _temp_4;
    int32_t _temp_5;
    int32_t _temp_6;

    _temp_0 = 1LL;
    _temp_1 = n <= _temp_0;
    if (_temp_1) goto if_true_2; else goto if_false_2;
    if_true_2:
    _temp_2 = 1LL;
    return _temp_2;
    goto if_end_2;
    if_false_2:
    goto if_end_2;
    if_end_2:
    _temp_3 = 1LL;
    _temp_4 = n - _temp_3;
    _temp_5 = factorial(_temp_4);
    _temp_6 = n * _temp_5;
    return _temp_6;
}

int main(void) {
    int64_t _temp_0;
    int32_t _temp_1;
    const char* _temp_2;
    int32_t _temp_4;
    const char* _temp_5;
    int32_t result;

    _temp_0 = 5LL;
    _temp_1 = factorial(_temp_0);
    result = _temp_1;
    _temp_2 = "Factorial of 5: ";
    falcon_print(_temp_2);
    falcon_print_int(result);
    _temp_5 = "";
    falcon_println(_temp_5);
    return 0;
}

