/* Generated by Falcon Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Falcon Runtime Declarations */
void falcon_panic(const char* msg);
void falcon_println(const char* s);
void falcon_print(const char* s);
void falcon_print_int(int64_t value);
void falcon_print_float(double value);
void* falcon_alloc(size_t size);
void falcon_dealloc(void* ptr);

/* Function Declarations */
int main(void);

int main(void) {
    int64_t _temp_0;
    int64_t _temp_1;
    const char* _temp_10;
    int64_t _temp_2;
    bool _temp_3;
    int32_t _temp_4;
    int64_t _temp_5;
    int32_t _temp_6;
    const char* _temp_7;
    int32_t _temp_9;
    int32_t i;
    int32_t sum;

    _temp_0 = 0LL;
    sum = _temp_0;
    _temp_1 = 1LL;
    i = _temp_1;
    _temp_2 = 11LL;
    for_start_1:
    _temp_3 = i < _temp_2;
    if (_temp_3) goto for_body_1; else goto for_end_1;
    for_body_1:
    _temp_4 = sum + i;
    sum = _temp_4;
    _temp_5 = 1LL;
    _temp_6 = i + _temp_5;
    i = _temp_6;
    goto for_start_1;
    for_end_1:
    _temp_7 = "Sum of 1 to 10 = ";
    falcon_print(_temp_7);
    falcon_print_int(sum);
    _temp_10 = "";
    falcon_println(_temp_10);
    return 0;
}

