/* Generated by Falcon Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Falcon Runtime Declarations */
void falcon_panic(const char* msg);
void falcon_println(const char* s);
void falcon_print(const char* s);
void falcon_print_int(int64_t value);
void falcon_print_float(double value);
void* falcon_alloc(size_t size);
void falcon_dealloc(void* ptr);

/* Function Declarations */
int main(void);

int main(void) {
    int64_t _temp_0;
    int64_t _temp_1;
    bool _temp_2;
    int32_t _temp_3;
    int32_t _temp_4;
    const char* _temp_5;
    int64_t _temp_7;
    int32_t _temp_8;
    const char* _temp_9;
    int32_t i;

    _temp_0 = 1LL;
    i = _temp_0;
    _temp_1 = 6LL;
    for_start_0:
    _temp_2 = i < _temp_1;
    if (_temp_2) goto for_body_0; else goto for_end_0;
    for_body_0:
    _temp_3 = i * i;
    falcon_print_int(_temp_3);
    _temp_5 = " ";
    falcon_print(_temp_5);
    _temp_7 = 1LL;
    _temp_8 = i + _temp_7;
    i = _temp_8;
    goto for_start_0;
    for_end_0:
    _temp_9 = "";
    falcon_println(_temp_9);
    return 0;
}

