/* Generated by Falcon Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Falcon Runtime Declarations */
void falcon_panic(const char* msg);
void falcon_println(const char* s);
void falcon_print(const char* s);
void falcon_print_int(int64_t value);
void falcon_print_float(double value);
void* falcon_alloc(size_t size);
void falcon_dealloc(void* ptr);

/* Function Declarations */
int main(void);

int main(void) {
    int64_t _temp_0;
    int64_t _temp_1;
    bool _temp_2;
    int32_t _temp_3;
    int64_t _temp_4;
    int32_t _temp_5;
    int32_t i;

    _temp_0 = 0LL;
    i = _temp_0;
    _temp_1 = 10LL;
    for_start_0:
    _temp_2 = i < _temp_1;
    if (_temp_2) goto for_body_0; else goto for_end_0;
    for_body_0:
    falcon_print_int(i);
    _temp_4 = 1LL;
    _temp_5 = i + _temp_4;
    i = _temp_5;
    goto for_start_0;
    for_end_0:
    return 0;
}

