/* Generated by Falcon Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Falcon Runtime Declarations */
void falcon_panic(const char* msg);
void falcon_println(const char* s);
void falcon_print(const char* s);
void falcon_print_int(int64_t value);
void falcon_print_float(double value);
void falcon_bounds_check(int64_t index, int64_t length);
void* falcon_alloc(size_t size);
void falcon_dealloc(void* ptr);

/* Function Declarations */
const char* input(const char* prompt);
const char* str_concat(const char* a, const char* b);
bool str_eq(const char* a, const char* b);
bool str_is_empty(const char* s);
int64_t str_len(const char* s);
int64_t str_find_from(const char* haystack, const char* needle, int64_t start);
const char* str_substr(const char* s, int64_t start, int64_t length);
const char* str_replace_all(const char* input, const char* target, const char* replacement);
const char* str_strip_html_tags(const char* input);
const char* str_json_extract_values(const char* json, const char* key, int64_t max_items);
int main(void);

const char* input(const char* prompt) {
    int32_t _temp_0;

    _temp_0 = falcon_input(prompt);
    return _temp_0;
}

const char* str_concat(const char* a, const char* b) {
    int32_t _temp_0;

    _temp_0 = falcon_str_concat(a, b);
    return _temp_0;
}

bool str_eq(const char* a, const char* b) {
    int32_t _temp_0;

    _temp_0 = falcon_str_eq(a, b);
    return _temp_0;
}

bool str_is_empty(const char* s) {
    int32_t _temp_0;

    _temp_0 = falcon_str_is_empty(s);
    return _temp_0;
}

int64_t str_len(const char* s) {
    int32_t _temp_0;

    _temp_0 = falcon_str_len(s);
    return _temp_0;
}

int64_t str_find_from(const char* haystack, const char* needle, int64_t start) {
    int32_t _temp_0;

    _temp_0 = falcon_str_find_from(haystack, needle, start);
    return _temp_0;
}

const char* str_substr(const char* s, int64_t start, int64_t length) {
    int32_t _temp_0;

    _temp_0 = falcon_str_substr(s, start, length);
    return _temp_0;
}

const char* str_replace_all(const char* input, const char* target, const char* replacement) {
    int32_t _temp_0;

    _temp_0 = falcon_str_replace_all(input, target, replacement);
    return _temp_0;
}

const char* str_strip_html_tags(const char* input) {
    int32_t _temp_0;

    _temp_0 = falcon_str_strip_html_tags(input);
    return _temp_0;
}

const char* str_json_extract_values(const char* json, const char* key, int64_t max_items) {
    int32_t _temp_0;

    _temp_0 = falcon_str_json_extract_values(json, key, max_items);
    return _temp_0;
}

int main(void) {
    const char* _temp_0;

    _temp_0 = "Hello, Falcon!";
    falcon_println(_temp_0);
    return 0;
}

