/* Generated by Falcon Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Falcon Runtime Declarations */
void falcon_panic(const char* msg);
void falcon_println(const char* s);
void falcon_print(const char* s);
void falcon_print_int(int64_t value);
void falcon_print_float(double value);
void falcon_bounds_check(int64_t index, int64_t length);
void* falcon_alloc(size_t size);
void falcon_dealloc(void* ptr);

/* Function Declarations */
const char* input(const char* prompt);
const char* str_concat(const char* a, const char* b);
bool str_eq(const char* a, const char* b);
bool str_is_empty(const char* s);
int64_t str_len(const char* s);
int64_t str_find_from(const char* haystack, const char* needle, int64_t start);
const char* str_substr(const char* s, int64_t start, int64_t length);
const char* str_replace_all(const char* input, const char* target, const char* replacement);
const char* str_strip_html_tags(const char* input);
const char* str_json_extract_values(const char* json, const char* key, int64_t max_items);
double sin(double x);
double cos(double x);
double tan(double x);
double asin(double x);
double acos(double x);
double atan(double x);
double sqrt(double x);
double pow(double base, double exp);
double exp(double x);
double log(double x);
double log10(double x);
double floor(double x);
double ceil(double x);
double round(double x);
double pi(void);
double e(void);
int64_t abs(int64_t value);
int64_t min(int64_t a, int64_t b);
int64_t max(int64_t a, int64_t b);
int main(void);

const char* input(const char* prompt) {
    int32_t _temp_0;

    _temp_0 = falcon_input(prompt);
    return _temp_0;
}

const char* str_concat(const char* a, const char* b) {
    int32_t _temp_0;

    _temp_0 = falcon_str_concat(a, b);
    return _temp_0;
}

bool str_eq(const char* a, const char* b) {
    int32_t _temp_0;

    _temp_0 = falcon_str_eq(a, b);
    return _temp_0;
}

bool str_is_empty(const char* s) {
    int32_t _temp_0;

    _temp_0 = falcon_str_is_empty(s);
    return _temp_0;
}

int64_t str_len(const char* s) {
    int32_t _temp_0;

    _temp_0 = falcon_str_len(s);
    return _temp_0;
}

int64_t str_find_from(const char* haystack, const char* needle, int64_t start) {
    int32_t _temp_0;

    _temp_0 = falcon_str_find_from(haystack, needle, start);
    return _temp_0;
}

const char* str_substr(const char* s, int64_t start, int64_t length) {
    int32_t _temp_0;

    _temp_0 = falcon_str_substr(s, start, length);
    return _temp_0;
}

const char* str_replace_all(const char* input, const char* target, const char* replacement) {
    int32_t _temp_0;

    _temp_0 = falcon_str_replace_all(input, target, replacement);
    return _temp_0;
}

const char* str_strip_html_tags(const char* input) {
    int32_t _temp_0;

    _temp_0 = falcon_str_strip_html_tags(input);
    return _temp_0;
}

const char* str_json_extract_values(const char* json, const char* key, int64_t max_items) {
    int32_t _temp_0;

    _temp_0 = falcon_str_json_extract_values(json, key, max_items);
    return _temp_0;
}

double sin(double x) {
    int32_t _temp_0;

    _temp_0 = falcon_sin(x);
    return _temp_0;
}

double cos(double x) {
    int32_t _temp_0;

    _temp_0 = falcon_cos(x);
    return _temp_0;
}

double tan(double x) {
    int32_t _temp_0;

    _temp_0 = falcon_tan(x);
    return _temp_0;
}

double asin(double x) {
    int32_t _temp_0;

    _temp_0 = falcon_asin(x);
    return _temp_0;
}

double acos(double x) {
    int32_t _temp_0;

    _temp_0 = falcon_acos(x);
    return _temp_0;
}

double atan(double x) {
    int32_t _temp_0;

    _temp_0 = falcon_atan(x);
    return _temp_0;
}

double sqrt(double x) {
    int32_t _temp_0;

    _temp_0 = falcon_sqrt(x);
    return _temp_0;
}

double pow(double base, double exp) {
    int32_t _temp_0;

    _temp_0 = falcon_pow(base, exp);
    return _temp_0;
}

double exp(double x) {
    int32_t _temp_0;

    _temp_0 = falcon_exp(x);
    return _temp_0;
}

double log(double x) {
    int32_t _temp_0;

    _temp_0 = falcon_log(x);
    return _temp_0;
}

double log10(double x) {
    int32_t _temp_0;

    _temp_0 = falcon_log10(x);
    return _temp_0;
}

double floor(double x) {
    int32_t _temp_0;

    _temp_0 = falcon_floor(x);
    return _temp_0;
}

double ceil(double x) {
    int32_t _temp_0;

    _temp_0 = falcon_ceil(x);
    return _temp_0;
}

double round(double x) {
    int32_t _temp_0;

    _temp_0 = falcon_round(x);
    return _temp_0;
}

double pi(void) {
    int32_t _temp_0;

    _temp_0 = falcon_pi();
    return _temp_0;
}

double e(void) {
    int32_t _temp_0;

    _temp_0 = falcon_e();
    return _temp_0;
}

int64_t abs(int64_t value) {
    int32_t _temp_0;

    _temp_0 = falcon_abs(value);
    return _temp_0;
}

int64_t min(int64_t a, int64_t b) {
    int32_t _temp_0;

    _temp_0 = falcon_min(a, b);
    return _temp_0;
}

int64_t max(int64_t a, int64_t b) {
    int32_t _temp_0;

    _temp_0 = falcon_max(a, b);
    return _temp_0;
}

int main(void) {
    const char* _temp_0;
    double _temp_10;
    int32_t _temp_11;
    int32_t _temp_12;
    int32_t _temp_13;
    const char* _temp_14;
    const char* _temp_16;
    double _temp_18;
    double _temp_19;
    const char* _temp_2;
    int32_t _temp_20;
    int32_t _temp_21;
    int32_t _temp_22;
    const char* _temp_23;
    const char* _temp_25;
    int32_t _temp_27;
    double _temp_28;
    int32_t _temp_29;
    int32_t _temp_30;
    int32_t _temp_31;
    const char* _temp_32;
    const char* _temp_34;
    int32_t _temp_36;
    double _temp_37;
    int32_t _temp_38;
    int32_t _temp_39;
    const char* _temp_4;
    int32_t _temp_40;
    const char* _temp_41;
    const char* _temp_43;
    const char* _temp_6;
    const char* _temp_8;

    _temp_0 = "=== Falcon Native Math Demo ===";
    falcon_println(_temp_0);
    _temp_2 = "(Same C library Python uses - native speed!)";
    falcon_println(_temp_2);
    _temp_4 = "";
    falcon_println(_temp_4);
    _temp_6 = "sqrt(16) = 4";
    falcon_println(_temp_6);
    _temp_8 = "  Result: ";
    falcon_print(_temp_8);
    _temp_10 = 16;
    _temp_11 = sqrt(_temp_10);
    falcon_print_float(_temp_11);
    _temp_13 = print_newline();
    _temp_14 = "pow(2, 10) = 1024";
    falcon_println(_temp_14);
    _temp_16 = "  Result: ";
    falcon_print(_temp_16);
    _temp_18 = 2;
    _temp_19 = 10;
    _temp_20 = pow(_temp_18, _temp_19);
    falcon_print_float(_temp_20);
    _temp_22 = print_newline();
    _temp_23 = "pi = 3.14159...";
    falcon_println(_temp_23);
    _temp_25 = "  Result (x1000): ";
    falcon_print(_temp_25);
    _temp_27 = pi();
    _temp_28 = 1000;
    _temp_29 = _temp_27 * _temp_28;
    falcon_print_float(_temp_29);
    _temp_31 = print_newline();
    _temp_32 = "e = 2.71828...";
    falcon_println(_temp_32);
    _temp_34 = "  Result (x1000): ";
    falcon_print(_temp_34);
    _temp_36 = e();
    _temp_37 = 1000;
    _temp_38 = _temp_36 * _temp_37;
    falcon_print_float(_temp_38);
    _temp_40 = print_newline();
    _temp_41 = "";
    falcon_println(_temp_41);
    _temp_43 = "Native math complete - no VM overhead!";
    falcon_println(_temp_43);
    return 0;
}

