/* Generated by Falcon Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Falcon Runtime Declarations */
void falcon_panic(const char* msg);
void falcon_println(const char* s);
void falcon_print(const char* s);
void falcon_print_int(int64_t value);
void falcon_print_float(double value);
void* falcon_alloc(size_t size);
void falcon_dealloc(void* ptr);

/* Function Declarations */
void shared_logic(void);
void baremetal_firmware(void);
int main(void);

void shared_logic(void) {
    const char* _temp_0;
    const char* _temp_2;

    _temp_0 = "Shared logic runs everywhere";
    falcon_print(_temp_0);
    _temp_2 = "";
    falcon_println(_temp_2);
}

void baremetal_firmware(void) {
    int32_t _temp_0;
    const char* _temp_1;
    const char* _temp_3;

    _temp_0 = shared_logic();
    _temp_1 = "Baremetal: Zero runtime, direct hardware";
    falcon_print(_temp_1);
    _temp_3 = "";
    falcon_println(_temp_3);
}

int main(void) {
    const char* _temp_0;
    const char* _temp_2;
    int32_t _temp_4;

    _temp_0 = "=== Falcon Multi-Profile Demo ===";
    falcon_print(_temp_0);
    _temp_2 = "";
    falcon_println(_temp_2);
    _temp_4 = shared_logic();
    return 0;
}

