/* Generated by Falcon Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Falcon Runtime Declarations */
void falcon_panic(const char* msg);
void falcon_println(const char* s);
void falcon_print(const char* s);
void falcon_print_int(int64_t value);
void falcon_print_float(double value);
void* falcon_alloc(size_t size);
void falcon_dealloc(void* ptr);

/* Function Declarations */
void shared_logic(void);
void app_main(void);
int main(void);

void shared_logic(void) {
    const char* _temp_0;

    _temp_0 = "Shared logic works!";
    falcon_println(_temp_0);
}

void app_main(void) {
    const char* _temp_0;
    int32_t _temp_2;

    _temp_0 = "Userland app running";
    falcon_println(_temp_0);
    _temp_2 = shared_logic();
}

int main(void) {
    const char* _temp_0;
    int32_t _temp_2;

    _temp_0 = "Demo program";
    falcon_println(_temp_0);
    _temp_2 = shared_logic();
    return 0;
}

