/* Generated by Falcon Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Falcon Runtime Declarations */
void falcon_panic(const char* msg);
void falcon_println(const char* s);
void falcon_print(const char* s);
void falcon_print_int(int64_t value);
void falcon_print_float(double value);
void* falcon_alloc(size_t size);
void falcon_dealloc(void* ptr);

/* Function Declarations */
int main(void);

int main(void) {
    int64_t _temp_0;
    int64_t _temp_1;
    const char* _temp_3;
    int32_t x;

    _temp_0 = 0LL;
    _temp_1 = 5LL;
    /* Range not supported in C backend */ _temp_2 = 0;
    x = _temp_2;
    _temp_3 = "done";
    falcon_println(_temp_3);
    return 0;
}

