/* Generated by Falcon Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Falcon Runtime Declarations */
void falcon_panic(const char* msg);
void falcon_println(const char* s);
void falcon_print(const char* s);
void falcon_print_int(int64_t value);
void falcon_print_float(double value);
void* falcon_alloc(size_t size);
void falcon_dealloc(void* ptr);

/* Function Declarations */
int64_t add(int64_t a, int64_t b);
int main(void);

int64_t add(int64_t a, int64_t b) {
    int32_t _temp_0;

    _temp_0 = a + b;
    return _temp_0;
}

int main(void) {
    int64_t _temp_0;
    int64_t _temp_1;
    int32_t _temp_2;
    const char* _temp_3;
    int32_t _temp_5;
    const char* _temp_6;
    int32_t result;

    _temp_0 = 5LL;
    _temp_1 = 3LL;
    _temp_2 = add(_temp_0, _temp_1);
    result = _temp_2;
    _temp_3 = "5 + 3 = ";
    falcon_print(_temp_3);
    falcon_print_int(result);
    _temp_6 = "";
    falcon_println(_temp_6);
    return 0;
}

