/* Generated by Falcon Compiler */
#include <stdio.h>
#include <stdlib.h>
#include <stdint.h>
#include <stdbool.h>
#include <string.h>

/* Falcon Runtime Declarations */
void falcon_panic(const char* msg);
void falcon_println(const char* s);
void falcon_print(const char* s);
void falcon_print_int(int64_t value);
void falcon_print_float(double value);
void* falcon_alloc(size_t size);
void falcon_dealloc(void* ptr);

/* Function Declarations */
int main(void);

int main(void) {
    const char* _temp_0;
    int32_t _temp_10;
    int32_t _temp_11;
    int32_t _temp_12;
    int32_t _temp_13;
    int32_t _temp_14;
    int32_t _temp_15;
    const char* _temp_16;
    int64_t _temp_18;
    int64_t _temp_19;
    int64_t _temp_2;
    int64_t _temp_20;
    int32_t _temp_21;
    int32_t _temp_22;
    const char* _temp_23;
    int64_t _temp_25;
    int64_t _temp_26;
    int64_t _temp_27;
    bool _temp_28;
    int32_t _temp_29;
    int64_t _temp_3;
    int64_t _temp_30;
    int32_t _temp_31;
    int32_t _temp_32;
    const char* _temp_33;
    int64_t _temp_35;
    int64_t _temp_37;
    bool _temp_38;
    int64_t _temp_39;
    struct Pair _temp_4;
    int32_t _temp_40;
    int64_t _temp_41;
    bool _temp_42;
    int64_t _temp_43;
    int32_t _temp_44;
    int64_t _temp_45;
    bool _temp_46;
    int64_t _temp_47;
    int32_t _temp_48;
    int64_t _temp_49;
    int64_t _temp_5;
    int32_t _temp_50;
    const char* _temp_51;
    int64_t _temp_53;
    int64_t _temp_54;
    bool _temp_55;
    int32_t _temp_56;
    int64_t _temp_57;
    int32_t _temp_58;
    const char* _temp_59;
    int64_t _temp_6;
    int64_t* _temp_61;
    int32_t _temp_62;
    int32_t _temp_63;
    int32_t _temp_64;
    int32_t _temp_65;
    int32_t _temp_66;
    int32_t _temp_67;
    const char* _temp_68;
    struct Point _temp_7;
    int64_t _temp_70;
    int64_t _temp_71;
    bool _temp_72;
    int64_t _temp_73;
    bool _temp_74;
    int64_t _temp_75;
    int32_t _temp_76;
    int64_t _temp_77;
    int32_t _temp_78;
    int64_t _temp_79;
    int32_t _temp_8;
    int32_t _temp_80;
    const char* _temp_81;
    int32_t _temp_9;
    int32_t arr;
    int32_t i;
    int32_t j;
    int32_t loopsum;
    int32_t p1;
    int32_t p2;
    int32_t sum;
    int32_t x;
    int32_t y;

    _temp_0 = "=== Struct Tests ===";
    falcon_println(_temp_0);
    _temp_2 = 10LL;
    _temp_3 = 20LL;
    /* init Pair */ _temp_4.a = _temp_2; _temp_4.b = _temp_3;
    p1 = _temp_4;
    _temp_5 = 5LL;
    _temp_6 = 7LL;
    /* init Point */ _temp_7.x = _temp_5; _temp_7.y = _temp_6;
    p2 = _temp_7;
    _temp_8 = p1.a;
    falcon_print_int(_temp_8);
    _temp_10 = p1.b;
    falcon_print_int(_temp_10);
    _temp_12 = p2.x;
    falcon_print_int(_temp_12);
    _temp_14 = p2.y;
    falcon_print_int(_temp_14);
    _temp_16 = "=== Arithmetic ===";
    falcon_println(_temp_16);
    _temp_18 = 0LL;
    sum = _temp_18;
    _temp_19 = 100LL;
    _temp_20 = 200LL;
    _temp_21 = _temp_19 + _temp_20;
    sum = _temp_21;
    falcon_print_int(sum);
    _temp_23 = "=== Loop ===";
    falcon_println(_temp_23);
    _temp_25 = 0LL;
    i = _temp_25;
    _temp_26 = 0LL;
    loopsum = _temp_26;
    loop_start_27:
    _temp_27 = 10LL;
    _temp_28 = i < _temp_27;
    if (_temp_28) goto loop_body_27; else goto loop_end_27;
    loop_body_27:
    _temp_29 = loopsum + i;
    loopsum = _temp_29;
    _temp_30 = 1LL;
    _temp_31 = i + _temp_30;
    i = _temp_31;
    goto loop_start_27;
    loop_end_27:
    falcon_print_int(loopsum);
    _temp_33 = "=== Match ===";
    falcon_println(_temp_33);
    _temp_35 = 2LL;
    x = _temp_35;
    _temp_37 = 1LL;
    _temp_38 = x == _temp_37;
    if (_temp_38) goto match_body_36_0; else goto match_check_36_1;
    match_body_36_0:
    _temp_39 = 100LL;
    falcon_print_int(_temp_39);
    goto match_end_36;
    match_check_36_1:
    _temp_41 = 2LL;
    _temp_42 = x == _temp_41;
    if (_temp_42) goto match_body_36_1; else goto match_check_36_2;
    match_body_36_1:
    _temp_43 = 200LL;
    falcon_print_int(_temp_43);
    goto match_end_36;
    match_check_36_2:
    _temp_45 = 3LL;
    _temp_46 = x == _temp_45;
    if (_temp_46) goto match_body_36_2; else goto match_check_36_3;
    match_body_36_2:
    _temp_47 = 300LL;
    falcon_print_int(_temp_47);
    goto match_end_36;
    match_check_36_3:
    match_body_36_3:
    _temp_49 = 999LL;
    falcon_print_int(_temp_49);
    goto match_end_36;
    match_end_36:
    _temp_51 = "=== For Loop ===";
    falcon_println(_temp_51);
    _temp_53 = 0LL;
    j = _temp_53;
    _temp_54 = 5LL;
    for_start_53:
    _temp_55 = j < _temp_54;
    if (_temp_55) goto for_body_53; else goto for_end_53;
    for_body_53:
    falcon_print_int(j);
    _temp_57 = 1LL;
    _temp_58 = j + _temp_57;
    j = _temp_58;
    goto for_start_53;
    for_end_53:
    _temp_59 = "=== Array ===";
    falcon_println(_temp_59);
    int64_t _temp_61_data[] = {10LL, 20LL, 30LL, 40LL, 50LL}; _temp_61 = _temp_61_data;
    arr = _temp_61;
    _temp_62 = arr[0LL];
    falcon_print_int(_temp_62);
    _temp_64 = arr[2LL];
    falcon_print_int(_temp_64);
    _temp_66 = arr[4LL];
    falcon_print_int(_temp_66);
    _temp_68 = "=== Nested Control ===";
    falcon_println(_temp_68);
    _temp_70 = 5LL;
    y = _temp_70;
    _temp_71 = 0LL;
    _temp_72 = y > _temp_71;
    if (_temp_72) goto if_true_73; else goto if_false_73;
    if_true_73:
    _temp_73 = 3LL;
    _temp_74 = y > _temp_73;
    if (_temp_74) goto if_true_75; else goto if_false_75;
    if_true_75:
    _temp_75 = 1000LL;
    falcon_print_int(_temp_75);
    goto if_end_75;
    if_false_75:
    _temp_77 = 500LL;
    falcon_print_int(_temp_77);
    goto if_end_75;
    if_end_75:
    goto if_end_73;
    if_false_73:
    _temp_79 = 0LL;
    falcon_print_int(_temp_79);
    goto if_end_73;
    if_end_73:
    _temp_81 = "=== STRESS TEST COMPLETE ===";
    falcon_println(_temp_81);
    return 0;
}

